"""Document generation / export.

Turns an analysis + optimized workflow into downloadable documents in several
formats: Markdown, plain text, HTML, and Word (.docx).

Markdown, text, and HTML have no external dependencies. The .docx format
requires python-docx (install via the `docs` extra: `uv add python-docx` or
`uv sync --extra docs`). The functions are pure where possible — Markdown/text/
HTML return strings; .docx returns bytes — so the UI can offer them as
downloads and the CLI can write them to disk.
"""

from __future__ import annotations

import io
from dataclasses import dataclass
from datetime import datetime

from ..utils.logger import get_logger

logger = get_logger(__name__)


@dataclass
class ExportPayload:
    """Everything a generated document might contain."""

    process_description: str
    analysis: str
    optimized: str
    comparison: str | None = None
    title: str = "Business Process Optimization Report"
    generated_at: str = ""

    def __post_init__(self) -> None:
        if not self.generated_at:
            self.generated_at = datetime.now().strftime("%Y-%m-%d %H:%M")


def to_markdown(payload: ExportPayload) -> str:
    """Render the report as a Markdown string."""
    parts = [
        f"# {payload.title}",
        "",
        f"*Generated: {payload.generated_at}*",
        "",
        "## Original Process",
        "",
        payload.process_description.strip(),
        "",
        "## Analysis",
        "",
        payload.analysis.strip(),
        "",
        "## Optimized Workflow",
        "",
        payload.optimized.strip(),
    ]
    if payload.comparison:
        parts += ["", "## Before / After Comparison", "", payload.comparison.strip()]
    parts += ["", "---", "", "_Generated by the Business Process Optimization app._"]
    return "\n".join(parts) + "\n"


def to_text(payload: ExportPayload) -> str:
    """Render the report as plain text (no Markdown syntax)."""

    def section(title: str, body: str) -> str:
        underline = "=" * len(title)
        return f"{title}\n{underline}\n{body.strip()}\n"

    blocks = [
        f"{payload.title}",
        f"Generated: {payload.generated_at}",
        "",
        section("ORIGINAL PROCESS", payload.process_description),
        section("ANALYSIS", payload.analysis),
        section("OPTIMIZED WORKFLOW", payload.optimized),
    ]
    if payload.comparison:
        blocks.append(section("BEFORE / AFTER COMPARISON", payload.comparison))
    return "\n".join(blocks)


def to_html(payload: ExportPayload) -> str:
    """Render the report as a self-contained, printable HTML string."""
    comparison_block = ""
    if payload.comparison:
        comparison_block = f"""
    <h2>Before / After Comparison</h2>
    <pre>{_escape(payload.comparison.strip())}</pre>"""

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>{_escape(payload.title)}</title>
<style>
  body {{ font-family: -apple-system, Segoe UI, Roboto, sans-serif;
          max-width: 820px; margin: 2rem auto; padding: 0 1rem; color: #1a1a1a; }}
  h1 {{ border-bottom: 3px solid #2563eb; padding-bottom: .3rem; }}
  h2 {{ color: #2563eb; margin-top: 1.8rem; }}
  pre {{ background: #f5f5f5; padding: 1rem; border-radius: 6px;
         white-space: pre-wrap; word-wrap: break-word; }}
  .meta {{ color: #666; font-style: italic; }}
  footer {{ margin-top: 2rem; color: #888; font-size: .85rem;
            border-top: 1px solid #ddd; padding-top: .8rem; }}
</style>
</head>
<body>
  <h1>{_escape(payload.title)}</h1>
  <p class="meta">Generated: {_escape(payload.generated_at)}</p>

  <h2>Original Process</h2>
  <pre>{_escape(payload.process_description.strip())}</pre>

  <h2>Analysis</h2>
  <pre>{_escape(payload.analysis.strip())}</pre>

  <h2>Optimized Workflow</h2>
  <pre>{_escape(payload.optimized.strip())}</pre>{comparison_block}

  <footer>Generated by the Business Process Optimization app.</footer>
</body>
</html>
"""


def to_docx(payload: ExportPayload) -> bytes:
    """Render the report as a Word .docx document, returned as bytes.

    Requires python-docx. Raises a clear error if it's not installed.
    """
    try:
        from docx import Document
        from docx.shared import Pt, RGBColor
    except ImportError as exc:  # pragma: no cover
        raise RuntimeError(
            "python-docx is not installed. Install it with: "
            "uv add python-docx  (or: uv sync --extra docs)"
        ) from exc

    doc = Document()
    doc.add_heading(payload.title, level=0)

    meta = doc.add_paragraph()
    run = meta.add_run(f"Generated: {payload.generated_at}")
    run.italic = True
    run.font.size = Pt(10)
    run.font.color.rgb = RGBColor(0x66, 0x66, 0x66)

    def add_section(heading: str, body: str) -> None:
        doc.add_heading(heading, level=1)
        for line in body.strip().splitlines():
            doc.add_paragraph(line)

    add_section("Original Process", payload.process_description)
    add_section("Analysis", payload.analysis)
    add_section("Optimized Workflow", payload.optimized)
    if payload.comparison:
        add_section("Before / After Comparison", payload.comparison)

    doc.add_paragraph()
    footer = doc.add_paragraph()
    frun = footer.add_run(
        "Generated by the Business Process Optimization app."
    )
    frun.italic = True
    frun.font.size = Pt(9)
    frun.font.color.rgb = RGBColor(0x88, 0x88, 0x88)

    buffer = io.BytesIO()
    doc.save(buffer)
    logger.info("Generated .docx report (%d bytes)", buffer.tell())
    return buffer.getvalue()


# Map of format name -> (renderer, file extension, is_binary)
FORMATS = {
    "markdown": (to_markdown, "md", False),
    "text": (to_text, "txt", False),
    "html": (to_html, "html", False),
    "docx": (to_docx, "docx", True),
}


def _escape(text: str) -> str:
    """Minimal HTML escaping for safe embedding in <pre> blocks."""
    return (
        text.replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
    )
